python ./src/main.py \
    --input_dir ./inputs/Data/ \
    --network_dir ./inputs/network_info/ \
    --output_dir ./outputs/ \
    --geneExpression_file_name GSE72056_gene569_cell4486.csv.gz \
    --compounds_modules_file_name M171_V3_connected_cmMat.csv \
    --modules_genes_file_name M171_V3_connected_reactions_genes.json \
    --experiment_name Flux \
    --n_epoch_all 150 \
    --n_epoch_scfea 100 \
    --n_epoch_mpo 50
